name: naikan
description: :)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.11.3
  charts_flutter: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
    - family: Leelawadee
      fonts:
        - asset: assets/leelawad.ttf
        - asset: assets/leelawdb.ttf
          weight: 700



