name: naikan
description: :)

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: "^0.12.0"
  flutter:
    sdk: flutter
  firebase_messaging: ^4.0.0+1
  event_bus: ^1.1.0
  configurable_expansion_tile: ^1.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker:
  charts_flutter: ^0.6.0
  flutter_calendar_carousel: ^1.3.16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - assets/cherry.png
  fonts:
    - family: Leelawadee
      fonts:
        - asset: assets/leelawad.ttf
        - asset: assets/leelawdb.ttf
          weight: 700
    - family: Cooper
      fonts:
        - asset: assets/Cooper.ttf


